import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import Resume from '../components/resume/Resume'
import Projects from '../components/projects/Projects'
import Skills from '../components/skills/Skills'
import Navigation from '../components/navigation/Navigation'
import MyInfo from '../components/myinfo/MyInfo'
import Contacts from '../components/contacts/Contacts'
import SendEmailToMe from '../components/contacts/sentemailtome/SendEmailToMe'
import { useSelector} from "react-redux";
import { RootState} from "../components/redux/store";
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const darkmode = useSelector((state: RootState) => state.darkMode.darkModeVal);
  console.log('Welcome to my portfolio website!🎉')
  const isOpen = useSelector((state: RootState) => state.openerState.openValue);
  
  return (
    <div className={darkmode ? 'dark' : ''}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={isOpen ? ' bg-white dark:bg-gray-600 overflow-hidden' 
                          : 'bg-white dark:bg-gray-600 overflow-scroll h-[100vh]'}>

        <div id='start'>
          <Navigation/>
        </div>

        <MyInfo />

        <Contacts />

        <section>
          <Skills/>
          <Projects />
          <Resume />
        </section>

        <SendEmailToMe />

        <Link href="#start">
          <div className='absolute bottom-5 right-5 w-10 cursor-pointer opacity-50 flex items-end justify-end animate-bounce'>
            <Image src="/arr.png" alt="arrow" width={100} height={100}
            className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer'/>
          </div>
        </Link>
      </main>
    </div>
  )
}
